server:
    protocol: 'http'
    hostname: 'localhost'
    port: 3000
database:
    client: 'postgresql'
    connection:
        database: 'some-database-name'
        host: '192.168.50.251'
        port: 3001
        user: 'db-username'
        password: 'db-password'
    migrations:
        tableName: 'knex_migrations'
        directory: './src/models/migrations'
    pool:
        min: 2
        max: 10